// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTWI8_VfegUbAvSbBygzlp7NiypybvoM',
    appId: '1:71958973484:web:5ca6d7dd2d0da8b80b9589',
    messagingSenderId: '71958973484',
    projectId: 'chessarena-e3c06',
    authDomain: 'chessarena-e3c06.firebaseapp.com',
    databaseURL: 'https://chessarena-e3c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chessarena-e3c06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR0boQ5rVR5pctQUWglX-xKfRTeXsrtZw',
    appId: '1:71958973484:android:66ee0358d1319f7b0b9589',
    messagingSenderId: '71958973484',
    projectId: 'chessarena-e3c06',
    databaseURL: 'https://chessarena-e3c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chessarena-e3c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3oys4-PMz-xzmtb3c59TSo7RuG6myGQ',
    appId: '1:71958973484:ios:61cffcec9bf75ff70b9589',
    messagingSenderId: '71958973484',
    projectId: 'chessarena-e3c06',
    databaseURL: 'https://chessarena-e3c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chessarena-e3c06.firebasestorage.app',
    iosBundleId: 'com.govindsankar.chessarena.chessarena',
  );
}
